package formularios;

import dao.DAONotas;
import javax.swing.JOptionPane;
import modelos.Notas;

public class IngresoNotas extends javax.swing.JInternalFrame {

    public IngresoNotas() {
        initComponents();
        cajaNombreEstudiante.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cajaNombreEstudiante = new javax.swing.JTextField();
        cajaNota2 = new javax.swing.JTextField();
        cajaNota3 = new javax.swing.JTextField();
        cajaNotaDefinitiva = new javax.swing.JTextField();
        cajaNota1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnIngresarNotas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ingreso Notas de Estudiantes");
        setPreferredSize(new java.awt.Dimension(500, 370));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Nombre Estudiante:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Nota 1:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Nota 2:");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Nota 3:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Definitiva:");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cajaNombreEstudiante.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        cajaNota2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        cajaNota3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cajaNota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNota3ActionPerformed(evt);
            }
        });

        cajaNotaDefinitiva.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        cajaNota1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        jLabel6.setText("Ingreso Notas de Estudiantes");

        btnIngresarNotas.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        btnIngresarNotas.setText("Ingresar");
        btnIngresarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNotasActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Semana2_Java\\17_Reto_5\\data\\Imagenes\\ingresoNotas.png")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 2, 9)); // NOI18N
        jLabel8.setText("A continuación podrá ingresar la información de las notas obtenidas por los estudiantes");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 2, 9)); // NOI18N
        jLabel9.setText("Recuerde que la nota mínima posible es cero (0) y la máxima es cinco (5).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(btnIngresarNotas))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaNotaDefinitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(63, 63, 63)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cajaNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cajaNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cajaNotaDefinitiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarNotas)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean esNumero(String text) {
        try {
            Double.parseDouble(text);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void btnIngresarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNotasActionPerformed
        String nomEstudiante = cajaNombreEstudiante.getText();
        String nota1 = cajaNota1.getText();
        String nota2 = cajaNota2.getText();
        String nota3 = cajaNota3.getText();
        String definitiva = cajaNotaDefinitiva.getText();
        boolean validacion1, validacionNota1, validacionNota2, validacionNota3, validacionNotaDef;

        if (nomEstudiante.isEmpty() || nota1.isEmpty() || nota2.isEmpty() || nota3.isEmpty() || definitiva.isEmpty()) {
            JOptionPane.showMessageDialog(cajaNombreEstudiante, "Todos los campos son obligatorios");
            validacion1 = false;
        } else {
            validacion1 = true;
        }
        if (esNumero(nota1) && esNumero(nota2) && esNumero(nota3) && esNumero(definitiva)) {
            DAONotas objDaoEstudiante = new DAONotas();
            Notas objEstudiante = new Notas();
            objEstudiante.setNombreestudiante(nomEstudiante);
            if (Double.parseDouble(nota1) >= 0 && Double.parseDouble(nota1) <= 5) {
                objEstudiante.setNota1(Double.parseDouble(nota1));
                validacionNota1 = true;
            } else {
                JOptionPane.showMessageDialog(cajaNota1, "La nota 1 ingresada no es valida, el rango permitido corresponde entre 0 y 5");
                cajaNota1.setText("");
                cajaNota1.requestFocus();
                validacionNota1 = false;
            }
            if (Double.parseDouble(nota2) >= 0 && Double.parseDouble(nota2) <= 5) {
                objEstudiante.setNota2(Double.parseDouble(nota2));
                validacionNota2 = true;
            } else {
                JOptionPane.showMessageDialog(cajaNota2, "La nota 2 ingresada no es valida, el rango permitido corresponde entre 0 y 5");
                cajaNota2.setText("");
                cajaNota2.requestFocus();
                validacionNota2 = false;
            }
            if (Double.parseDouble(nota3) >= 0 && Double.parseDouble(nota3) <= 5) {
                objEstudiante.setNota3(Double.parseDouble(nota3));
                validacionNota3 = true;
            } else {
                JOptionPane.showMessageDialog(cajaNota3, "La nota 3 ingresada no es valida, el rango permitido corresponde entre 0 y 5");
                cajaNota3.setText("");
                cajaNota3.requestFocus();
                validacionNota3 = false;
            }
            if (Double.parseDouble(definitiva) >= 0 && Double.parseDouble(definitiva) <= 5) {
                objEstudiante.setDefinitiva(Double.parseDouble(definitiva));
                validacionNotaDef = true;
            } else {
                JOptionPane.showMessageDialog(cajaNotaDefinitiva, "La nota definitiva ingresada no es valida, el rango permitido corresponde entre 0 y 5");
                cajaNotaDefinitiva.setText("");
                cajaNotaDefinitiva.requestFocus();
                validacionNotaDef = false;
            }
            if (validacion1 == true && validacionNota1 == true && validacionNota2 == true && validacionNota3 == true && validacionNotaDef == true) {
                objDaoEstudiante.agregar(objEstudiante);
                cajaNombreEstudiante.setText("");
                cajaNota1.setText("");
                cajaNota2.setText("");
                cajaNota3.setText("");
                cajaNotaDefinitiva.setText("");
                JOptionPane.showMessageDialog(cajaNombreEstudiante, "Estudiante Agregado Correctamente");
            } else {
                JOptionPane.showMessageDialog(cajaNombreEstudiante, "No fue posible agregar el estudiante");
            }
            cajaNombreEstudiante.requestFocus();
        } else {
            JOptionPane.showMessageDialog(cajaNombreEstudiante, "Los valores correspondientes a las notas deben ser númericos");
            JOptionPane.showMessageDialog(cajaNombreEstudiante, "No fue posible agregar el estudiante");
        }
    }//GEN-LAST:event_btnIngresarNotasActionPerformed

    private void cajaNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNota3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarNotas;
    private javax.swing.JTextField cajaNombreEstudiante;
    private javax.swing.JTextField cajaNota1;
    private javax.swing.JTextField cajaNota2;
    private javax.swing.JTextField cajaNota3;
    private javax.swing.JTextField cajaNotaDefinitiva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
